In [1]:
import glob
import re
from pathlib import PurePath

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from IPython.display import display

pd.set_option('display.max_columns', 200)
pd.set_option('display.width', 180)
sns.set_theme(style='whitegrid')

In [2]:
# 1) 读取五个模型输出
csv_files = glob.glob(
    'f:/FINAL/Resume_Dataset_scrapped_from_livecareer/Resume/**/*evaluated_full.csv',
    recursive=True,
)
print('Found csv files:', csv_files)

frames = []
for path in csv_files:
    basename = PurePath(path).name
    m = re.search(r'^(.*?_?[^_]+?)-Resume_sampled_50_with_Variants_evaluated_full\.csv$', basename)
    model_name = m.group(1) if m else PurePath(path).stem

    dfp = pd.read_csv(path)
    dfp['model'] = model_name
    frames.append(dfp)

all_df = pd.concat(frames, ignore_index=True)
print('Total records:', len(all_df))

# 修复 religion: None -> NaN 的问题
if 'religion' in all_df.columns:
    all_df['religion'] = (
        all_df['religion']
        .astype('string')
        .str.strip()
        .replace({'': pd.NA, 'None': pd.NA, 'none': pd.NA})
        .fillna('No religion')
    )

# 分数字段转数值（稳妥）
score_cols = ['technical_score', 'experience_score', 'stability_score', 'overall_score']
for c in score_cols + ['screening_decision']:
    if c in all_df.columns:
        all_df[c] = pd.to_numeric(all_df[c], errors='coerce')

required = ['model', 'category', 'screening_decision', 'technical_score', 'experience_score', 'stability_score', 'overall_score']
missing = [c for c in required if c not in all_df.columns]
if missing:
    raise ValueError(f'Missing required columns: {missing}')

group_vars = [c for c in ['gender', 'age_group', 'nationality', 'religion', 'marital_status', 'volunteer_type'] if c in all_df.columns]
print('Group vars:', group_vars)

Found csv files: ['f:/FINAL/Resume_Dataset_scrapped_from_livecareer/Resume\\DeepSeek-V3.2-Resume_sampled_50_with_Variants_evaluated_full.csv', 'f:/FINAL/Resume_Dataset_scrapped_from_livecareer/Resume\\gemini-2.5-flash-Resume_sampled_50_with_Variants_evaluated_full.csv', 'f:/FINAL/Resume_Dataset_scrapped_from_livecareer/Resume\\gpt-5-mini-Resume_sampled_50_with_Variants_evaluated_full.csv', 'f:/FINAL/Resume_Dataset_scrapped_from_livecareer/Resume\\grok-4-fast-Resume_sampled_50_with_Variants_evaluated_full.csv', 'f:/FINAL/Resume_Dataset_scrapped_from_livecareer/Resume\\mistral-small-2603-Resume_sampled_50_with_Variants_evaluated_full.csv']
Total records: 3750
Group vars: ['gender', 'age_group', 'nationality', 'religion', 'marital_status', 'volunteer_type']

In [3]:
# ================================
# Ⅳ. Counterfactual Bias（反事实偏见）
# ================================

import numpy as np

def compute_counterfactual_metrics(
    df,
    id_col='original_id',
    score_col='overall_score',
    decision_col='screening_decision',
    model_col='model',
):
    rows = []

    for model_name, d_model in df.groupby(model_col):

        grouped = d_model.groupby(id_col)

        score_diffs = []
        flip_flags = []

        for oid, g in grouped:

            # 至少要有多个 variant
            if len(g) < 2:
                continue

            scores = g[score_col].dropna().values
            decisions = g[decision_col].dropna().values

            # ---------- 1️⃣ score diff ----------
            if len(scores) > 0:
                diff = float(np.max(scores) - np.min(scores))
                score_diffs.append(diff)

            # ---------- 2️⃣ flip ----------
            if len(decisions) > 0:
                unique_decisions = set(decisions)
                flip = int(0 in unique_decisions and 1 in unique_decisions)
                flip_flags.append(flip)

        # 汇总
        mean_score_diff = np.mean(score_diffs) if score_diffs else 0.0
        flip_rate = np.mean(flip_flags) if flip_flags else 0.0

        rows.append({
            'model': model_name,
            'cf_mean_score_diff': mean_score_diff,
            'cf_flip_rate': flip_rate,
            'num_resumes': len(score_diffs),
        })

    return pd.DataFrame(rows)

In [4]:
# ---------- 运行 ----------
cf_df = compute_counterfactual_metrics(all_df)

# 排序（优先看最不公平的）
cf_df = cf_df.sort_values('cf_flip_rate', ascending=False)

# 保存
cf_df.to_csv('counterfactual_bias_summary.csv', index=False)

print('\n=== Counterfactual Bias Summary ===')
display(cf_df)

=== Counterfactual Bias Summary ===

                model  cf_mean_score_diff  cf_flip_rate  num_resumes
3         grok-4-fast                1.36          0.32           50
2          gpt-5-mini                1.40          0.30           50
1    gemini-2.5-flash                1.36          0.28           50
4  mistral-small-2603                1.06          0.24           50
0       DeepSeek-V3.2                0.76          0.12           50

In [9]:
import numpy as np

def compute_counterfactual_metrics(
    df,
    id_col='original_id',
    score_cols=['overall_score', 'technical_score', 'experience_score', 'stability_score'],  # 传入多个维度
    decision_col='screening_decision',
    model_col='model',
):
    rows = []

    for model_name, d_model in df.groupby(model_col):
        grouped = d_model.groupby(id_col)

        # 准备存储每个维度
        score_diffs_dict = {c: [] for c in score_cols}
        flip_flags = []

        for oid, g in grouped:
            if len(g) < 2:
                continue

            # ---------- 1️⃣ score diff for each dimension ----------
            for c in score_cols:
                scores = g[c].dropna().values
                if len(scores) > 0:
                    diff = float(np.max(scores) - np.min(scores))
                    score_diffs_dict[c].append(diff)

            # ---------- 2️⃣ flip ----------
            decisions = g[decision_col].dropna().values
            if len(decisions) > 0:
                unique_decisions = set(decisions)
                flip = int(0 in unique_decisions and 1 in unique_decisions)
                flip_flags.append(flip)

        # 汇总每个维度
        row = {'model': model_name, 'cf_flip_rate': np.mean(flip_flags) if flip_flags else 0.0,
               'num_resumes': len(grouped)}
        for c in score_cols:
            row[f'cf_mean_diff_{c}'] = np.mean(score_diffs_dict[c]) if score_diffs_dict[c] else 0.0

        rows.append(row)

    return pd.DataFrame(rows)

In [10]:
score_cols = ['overall_score', 'technical_score', 'experience_score', 'stability_score']
cf_metrics_df = compute_counterfactual_metrics(all_df, score_cols=score_cols)
display(cf_metrics_df)

                model  cf_flip_rate  num_resumes  cf_mean_diff_overall_score  cf_mean_diff_technical_score  cf_mean_diff_experience_score  cf_mean_diff_stability_score
0       DeepSeek-V3.2          0.12           50                        0.76                          0.36                           0.78                          1.38
1    gemini-2.5-flash          0.28           50                        1.36                          1.10                           1.40                          1.66
2          gpt-5-mini          0.30           50                        1.40                          1.40                           1.40                          2.20
3         grok-4-fast          0.32           50                        1.36                          1.06                           1.50                          2.06
4  mistral-small-2603          0.24           50                        1.06                          0.58                           1.02                          1.66